[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# A GitHub repo to push Homebrew formulas to
tap = "rust-mcp-stack/homebrew-tap"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "~/.rust-mcp-stack/bin"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Whether to install an updater program
install-updater = false
# Whether dist should create a Github Release or use an existing draft
create-release = false

[dist.github-custom-runners]
global = "ubuntu-22.04"

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
global = "ubuntu-22.04"
runner = "ubuntu-22.04"

[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-22.04"
container = { image = "quay.io/pypa/manylinux_2_28_x86_64", host = "x86_64-unknown-linux-musl" }
