name: CI
on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  rust_check:
    name: Rust check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}
          restore-keys: ${{ runner.os }}-rust-

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - uses: davidB/rust-cargo-make@v1
      - uses: taiki-e/install-action@nextest

      - name: Run cargo make check
        run: |
          cargo make run-checks

      - name: Spell Check
        env:
          RUSTDOCFLAGS: "-Dwarnings"
        uses: crate-ci/typos@master

      - name: Audit
        uses: actions-rust-lang/audit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
